apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  # Sem nodeSelector / interfaces / serviceSelector => casa com todo Service
  # do tipo LB em todo node/interface. Tranquilo pra este cluster single-node.
